import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
  });
const nunito = Nunito({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Ebooks Unitec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col bg-secondary w-scree ${nunito.className} ${montserrat.variable}`}
      >
           <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
